-- FuelPro active-session fencing / stale offline write protection.
-- The most recently active session for a user+station owns a short server-side
-- lease and a monotonically increasing fence token. Offline sessions may keep
-- working locally, but they cannot publish an old snapshot after another
-- session has become active.
--
-- This is deliberately server-authoritative: client clocks are never used to
-- decide which session wins.

create table if not exists public.station_active_sessions (
  owner_id uuid not null references auth.users(id) on delete cascade,
  station_id uuid not null references public.stations(id) on delete cascade,
  session_id text not null,
  fence_token bigint not null default 1,
  last_heartbeat_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '60 seconds'),
  updated_at timestamptz not null default now(),
  primary key (owner_id, station_id)
);

create index if not exists station_active_sessions_expiry_idx
  on public.station_active_sessions (expires_at);

create table if not exists public.station_sync_conflicts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  station_id uuid not null references public.stations(id) on delete cascade,
  session_id text not null,
  active_session_id text,
  fence_token bigint,
  key text,
  reason text not null,
  detected_at timestamptz not null default now()
);

create index if not exists station_sync_conflicts_lookup_idx
  on public.station_sync_conflicts (owner_id, station_id, detected_at desc);

alter table public.station_active_sessions enable row level security;
alter table public.station_sync_conflicts enable row level security;

drop policy if exists "Users can view their active station sessions"
  on public.station_active_sessions;
create policy "Users can view their active station sessions"
  on public.station_active_sessions
  for select
  to authenticated
  using (owner_id = auth.uid());

drop policy if exists "Users can view their station sync conflicts"
  on public.station_sync_conflicts;
create policy "Users can view their station sync conflicts"
  on public.station_sync_conflicts
  for select
  to authenticated
  using (owner_id = auth.uid());

revoke all on public.station_active_sessions from anon, authenticated;
revoke all on public.station_sync_conflicts from anon, authenticated;
grant select on public.station_active_sessions to authenticated;
grant select on public.station_sync_conflicts to authenticated;

-- Claim/refresh the station lease. A second session cannot take over while
-- the current lease is alive. Once the lease expires, the new session becomes
-- the active session and receives a higher fence token.
create or replace function public.claim_station_active_session(
  p_station_id uuid,
  p_session_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_owner uuid := (select auth.uid());
  v_row public.station_active_sessions%rowtype;
  v_now timestamptz := now();
  v_new_token bigint;
begin
  if v_owner is null then
    raise exception 'AUTHENTICATION_REQUIRED';
  end if;
  if p_station_id is null or nullif(trim(p_session_id), '') is null then
    raise exception 'STATION_AND_SESSION_REQUIRED';
  end if;

  -- Only permit sessions for stations this user can already reach. This keeps
  -- the security-definer function from becoming a station-discovery/write
  -- primitive.
  if not exists (
    select 1
      from public.stations s
     where s.id = p_station_id
       and (
         s.owner_id = v_owner
         or exists (
           select 1
             from public.app_kv k
            where k.station_id = s.id
              and k.owner_id = v_owner
         )
       )
  ) then
    raise exception 'STATION_ACCESS_DENIED';
  end if;

  select *
    into v_row
    from public.station_active_sessions
   where owner_id = v_owner
     and station_id = p_station_id
   for update;

  if not found then
    insert into public.station_active_sessions (
      owner_id, station_id, session_id, fence_token,
      last_heartbeat_at, expires_at, updated_at
    )
    values (
      v_owner, p_station_id, trim(p_session_id), 1,
      v_now, v_now + interval '60 seconds', v_now
    );

    return jsonb_build_object(
      'granted', true,
      'session_id', trim(p_session_id),
      'fence_token', 1,
      'expires_at', (v_now + interval '60 seconds')::text,
      'previous_session_id', null
    );
  end if;

  if v_row.session_id = trim(p_session_id)
     or v_row.expires_at <= v_now then
    v_new_token := case
      when v_row.session_id = trim(p_session_id) then v_row.fence_token
      else v_row.fence_token + 1
    end;

    update public.station_active_sessions
       set session_id = trim(p_session_id),
           fence_token = v_new_token,
           last_heartbeat_at = v_now,
           expires_at = v_now + interval '60 seconds',
           updated_at = v_now
     where owner_id = v_owner
       and station_id = p_station_id;

    return jsonb_build_object(
      'granted', true,
      'session_id', trim(p_session_id),
      'fence_token', v_new_token,
      'expires_at', (v_now + interval '60 seconds')::text,
      'previous_session_id',
        case when v_row.session_id = trim(p_session_id)
             then null else v_row.session_id end
    );
  end if;

  insert into public.station_sync_conflicts (
    owner_id, station_id, session_id, active_session_id,
    fence_token, reason
  )
  values (
    v_owner, p_station_id, trim(p_session_id), v_row.session_id,
    v_row.fence_token, 'ACTIVE_SESSION_FENCED'
  );

  return jsonb_build_object(
    'granted', false,
    'session_id', trim(p_session_id),
    'active_session_id', v_row.session_id,
    'fence_token', v_row.fence_token,
    'expires_at', v_row.expires_at::text
  );
end;
$function$;

revoke all on function public.claim_station_active_session(uuid, text) from public, anon;
grant execute on function public.claim_station_active_session(uuid, text) to authenticated;

-- Central guarded write path. The old six-argument RPC remains available for
-- unscoped/global rows, but station-scoped callers must use this function.
create or replace function public.upsert_app_kv_session_versioned(
  p_id text,
  p_owner_id uuid,
  p_station_id uuid,
  p_collection text,
  p_data jsonb,
  p_expected_version bigint,
  p_session_id text,
  p_fence_token bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_active public.station_active_sessions%rowtype;
  v_existing_version bigint;
  v_existing_data jsonb;
  v_existing_updated timestamptz;
  v_new_version bigint;
  v_inserted boolean := false;
begin
  if (select auth.uid()) is null or p_owner_id <> (select auth.uid()) then
    raise exception 'OWNER_AUTHENTICATION_MISMATCH';
  end if;

  if p_station_id is null then
    raise exception 'STATION_REQUIRED_FOR_SESSION_GUARDED_WRITE';
  end if;

  select *
    into v_active
    from public.station_active_sessions
   where owner_id = p_owner_id
     and station_id = p_station_id
   for update;

  if not found
     or v_active.session_id <> trim(p_session_id)
     or v_active.fence_token <> p_fence_token
     or v_active.expires_at <= now() then
    insert into public.station_sync_conflicts (
      owner_id, station_id, session_id, active_session_id,
      fence_token, key, reason
    )
    values (
      p_owner_id, p_station_id, coalesce(trim(p_session_id), ''),
      case when found then v_active.session_id else null end,
      case when found then v_active.fence_token else null end,
      p_id, 'STALE_SESSION_WRITE_BLOCKED'
    );
    raise exception 'STALE_SESSION_WRITE_BLOCKED';
  end if;

  -- Refresh the lease as part of a successful write.
  update public.station_active_sessions
     set last_heartbeat_at = now(),
         expires_at = now() + interval '60 seconds',
         updated_at = now()
   where owner_id = p_owner_id
     and station_id = p_station_id;

  select version, data, updated_at
    into v_existing_version, v_existing_data, v_existing_updated
    from public.app_kv
   where id = p_id
     and owner_id = p_owner_id
   for update;

  if not found then
    begin
      insert into public.app_kv (
        id, collection, owner_id, station_id, data, version, updated_at
      )
      values (
        p_id, p_collection, p_owner_id, p_station_id, p_data, 1, now()
      );
      v_inserted := true;
    exception
      when unique_violation then
        v_inserted := false;
    end;

    if v_inserted then
      return jsonb_build_object(
        'ok', true, 'id', p_id, 'version', 1,
        'updated_at', now()::text, 'data', p_data
      );
    end if;

    select version, data, updated_at
      into v_existing_version, v_existing_data, v_existing_updated
      from public.app_kv
     where id = p_id
       and owner_id = p_owner_id
     for update;

    if not found then
      raise exception 'APP_KV_ROW_DISAPPEARED';
    end if;
  end if;

  if p_expected_version is null
     or p_expected_version = 0
     or v_existing_version = p_expected_version then
    v_new_version := v_existing_version + 1;

    update public.app_kv
       set data = p_data,
           station_id = p_station_id,
           collection = coalesce(p_collection, collection),
           version = v_new_version,
           updated_at = now()
     where id = p_id
       and owner_id = p_owner_id;

    return jsonb_build_object(
      'ok', true, 'id', p_id, 'version', v_new_version,
      'updated_at', now()::text, 'data', p_data
    );
  end if;

  return jsonb_build_object(
    'ok', false, 'id', p_id, 'version', v_existing_version,
    'updated_at', v_existing_updated::text, 'data', v_existing_data
  );
end;
$function$;

revoke all on function public.upsert_app_kv_session_versioned(
  text, uuid, uuid, text, jsonb, bigint, text, bigint
) from public, anon;
grant execute on function public.upsert_app_kv_session_versioned(
  text, uuid, uuid, text, jsonb, bigint, text, bigint
) to authenticated;

-- Fail closed for the legacy RPC when it is asked to write station-scoped
-- data. This is important: old clients must not be able to bypass the fence.
create or replace function public.upsert_app_kv_versioned(
  p_id text,
  p_owner_id uuid,
  p_station_id text,
  p_collection text,
  p_data jsonb,
  p_expected_version bigint
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if p_station_id is not null then
    raise exception 'ACTIVE_SESSION_REQUIRED';
  end if;

  raise exception 'LEGACY_GLOBAL_APP_KV_WRITE_DISABLED';
end;
$function$;

revoke all on function public.upsert_app_kv_versioned(
  text, uuid, text, text, jsonb, bigint
) from public, anon;
grant execute on function public.upsert_app_kv_versioned(
  text, uuid, text, text, jsonb, bigint
) to authenticated;

-- Verify the intended objects exist after migration.
do $verify$
begin
  if not exists (
    select 1 from pg_proc
     where proname = 'claim_station_active_session'
  ) then
    raise exception 'active session claim function missing';
  end if;
  if not exists (
    select 1 from pg_proc
     where proname = 'upsert_app_kv_session_versioned'
  ) then
    raise exception 'guarded app_kv write function missing';
  end if;
end;
$verify$;
